### ISSUE TITLE
Can't manually remove roles awarded via xp system

### ISSUE THREAD

**Issue by lalonro** [cookkkie/mee6#39]
Hi there!
Our server has Mee6 set up with the xp module, and we have it set to award a new role every five or so levels. However, we're having an issue where once a member levels up and gets the new role, they retain the old one. We tried to manually remove the old role so that they would only have the new one, but the bot automatically adds it back every time. So my main question was, is there a way to fix this?

**Comment by SilBoydens** [comment]
this is a know thing, Mee6 will check every 30 seconds if someone need to receive a role because his level is high enough. so if you remove a reward rank from someone he will just add it back. in one of the future update you will be able to set that they need to lose there old reward ranks when they get a new one(so not yet). 

for faster responses on your questions about mee6 ask in our discord server: https://discord.gg/0tOgeGSG9kYFepgL
^^on the dashboard click the `Support` button on top to get the sa

**Comment by lalonro** [comment]
Alrighty then, thank you for replying!
